Prism\PollBundle\Entity\BasePoll:
  type: mappedSuperclass
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: false
      gedmo:
        - sluggable
    slug:
      type: string
      length: 255
      nullable: false
      gedmo:
        slug:
          fields: [name]
          separator: -
    published:
      type: boolean
    closed:
      type: boolean
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update